Repository andela/eagle-bn-backend, pull requests merged in 2019-10, with the labels that each got.

#5 #168805561 git hooks
  .eslintignore
  .eslintrc.json
  .github/COMMIT_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: Ready For Review

#6 #168781795 setup hound CI
  .hound.yml
  README.md
Labels: Ready For Review

#11 [Fixes #168781797] setup-unit-test
  .babelrc
  .eslintrc.json
  package-lock.json
  package.json
  src/config/index.js
  src/config/passport.js
  src/index.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/tests/unitTest.js
Labels: Ready For Review

#10 chore(setup-documentation) setup swagger documentation
  .eslintrc.json
  package.json
  src/index.js
  src/utils/swaggerDefinition.js
Labels: Ready For Review

#12 #168781802 integrate app with heroku
  app.json
  package.json
  src/index.js
Labels: Ready For Review

#14 168781792 chore setup sequelize as our ORM
  package.json
  src/database/config.js
  src/database/migrations/20191001134213-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20191002082223-User.js
Labels: Ready For Review

#15 #168781798 setup dotenv
  .env.sample
  app.json
  package.json
  src/config/index.js
  src/index.js
Labels: Ready For Review

#3 #168781799 Integrate coveralls and coverall script in package
  .coveralls.yml
  .sequelizerc
  README.md
  package.json
Labels: Ready For Review

#16 #168781796 integrate travis
  .travis.yml
  README.md
Labels: Ready For Review

#18 #168929544 solve bug in documentation setup
  src/index.js
Labels: Ready For Review, bug

#19 #168928422 integrate with code climate
  README.md
  package.json
Labels: Ready For Review

#17 #168781801 docker setup
  .dockerignore
  .env.sample
  README.md
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  dockerfile
  package.json
Labels: Ready For Review

#20 #168781803 signup endpoint
  README.md
  app.json
  package.json
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/models/user.js
  src/index.js
  src/middlewares/userMiddlware.js
  src/routes/index.js
  src/routes/userRoutes.js
  src/tests/helper.spec.js
  src/tests/mockData/signupMockupData.js
  src/tests/signup.spec.js
  src/tests/unitTest.js
  src/utils/helper.js
  src/utils/sendResult.js
  src/utils/stringHelper.js
  src/utils/swaggerDefinition.js
  src/utils/validator.js
  src/validation/signupValidation.js
Labels: Ready For Review

#21 #168781806 login endpoint
  package.json
  src/controllers/userController.js
  src/database/config.js
  src/database/models/user.js
  src/database/seeders/20191002082223-User.js
  src/middlewares/userMiddlware.js
  src/routes/userRoutes.js
  src/tests/mockData/loginMockData.js
  src/tests/testsLogin.spec.js
Labels: Ready For Review

#22 #168781804 email verification
  .env.sample
  .travis.yml
  package.json
  src/config/index.js
  src/controllers/index.js
  src/controllers/userController.js
  src/index.js
  src/routes/userRoutes.js
  src/tests/signup.spec.js
  src/tests/verifyEmail.spec.js
  src/utils/email.js
  src/utils/helper.js
  src/utils/index.js
  src/utils/stringHelper.js
  src/validation/index.js
Labels: Ready For Review

#25 #168781808 implement user password reset
  .eslintrc.json
  docker-compose.yml
  package.json
  src/config/index.js
  src/controllers/email.js
  src/database/seeders/20191002082223-User.js
  src/middlewares/userMiddlware.js
  src/routes/userRoutes.js
  src/tests/mail.spec.js
  src/tests/mockData/email.js
  src/utils/email.js
  src/utils/emailHelper.js
  src/utils/helper.js
  src/utils/validator.js
Labels: Done With Feedback, Ready For Review

#26 #168781807 setup social login
  .DS_Store
  package.json
  src/.DS_Store
  src/config/auth.js
  src/config/passport.js
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/index.js
  src/middlewares/index.js
  src/routes/userRoutes.js
  src/tests/.DS_Store
  src/tests/mockData/profile.js
  src/tests/testsLogin.spec.js
  src/utils/OAuthCallback.js
  src/utils/swaggerDefinition.js
Labels: Ready For Review

#27 #168781816 integrate request models
  .DS_Store
  .codeclimate.yml
  .gitignore
  src/.DS_Store
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/migrations/20191014194106-request.js
  src/database/migrations/20191014194111-trip.js
  src/database/models/index.js
  src/database/models/request.js
  src/database/models/trip.js
  src/database/seeders/20191014191039-request.js
  src/database/seeders/20191014192244-trip.js
  src/middlewares/index.js
  src/routes/index.js
  src/routes/requestRoutes.js
  src/tests/.DS_Store
  src/tests/request.model.spec.js
  src/utils/email.js
Labels: Ready For Review

#29 #168781836 Users can view or create their accommodation facilities
  .env.sample
  .gitignore
  package.json
  src/config/clound-config.js
  src/controllers/accommodationController.js
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/migrations/20191001134215-create-accommodation.js
  src/database/migrations/20191001134218-create-accommodation-image.js
  src/database/models/Accommodations.js
  src/database/models/accommodationImage.js
  src/database/models/user.js
  src/database/seeders/20191002082223-User.js
  src/middlewares/accommodationMiddleware.js
  src/middlewares/userMiddlware.js
  src/routes/accommodationRoute.js
  src/routes/index.js
  src/tests/accommodation.spec.js
  src/tests/mockData/img.jpeg
  src/tests/mockData/img2.jpeg
  src/utils/helper.js
  src/utils/validator.js
Labels: Ready For Review

#30 #168781811 implement update-profile user update profile details
  .eslintrc.json
  .gitignore
  package.json
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/models/user.js
  src/index.js
  src/middlewares/accommodationMiddleware.js
  src/middlewares/userMiddlware.js
  src/routes/accommodationRoute.js
  src/routes/userRoutes.js
  src/tests/mail.spec.js
  src/tests/mockData/img.mp3
  src/tests/mockData/img.png
  src/tests/mockData/img.svg
  src/tests/signup.spec.js
  src/tests/users.spec.js
  src/utils/validator.js
  src/validation/index.js
  src/validation/signupValidation.js
Labels: Ready For Review

#31 #168781818 change role
  .babelrc
  .codeclimate.yml
  package.json
  src/controllers/role.js
  src/controllers/userController.js
  src/database/migrations/20191021100122-role.js
  src/database/migrations/20191021161639-add_colum_roleId.js
  src/database/models/role.js
  src/database/models/user.js
  src/database/seeders/20191001165157-demo-role.js
  src/database/seeders/20191002082223-User.js
  src/database/seeders/20191002082224-User.js
  src/middlewares/checkAdminRole.js
  src/middlewares/checkIsverified.js
  src/middlewares/userMiddlware.js
  src/routes/userRoutes.js
  src/tests/helper.spec.js
  src/tests/role.spec.js
  src/utils/stringHelper.js
  src/validation/checkRoles.js
Labels: Ready For Review

#32 #168781820 a manager can approve/reject a pending request
  package.json
  src/controllers/requestController.js
  src/database/migrations/20191014194119-add-lineManager-column.js
  src/database/models/user.js
  src/database/seeders/20191002082224-User.js
  src/database/seeders/20191014191039-request.js
  src/middlewares/accommodationMiddleware.js
  src/middlewares/requestMiddlware.js
  src/middlewares/rolesMiddlewares.js
  src/routes/accommodationRoute.js
  src/routes/requestRoutes.js
  src/tests/accommodation.spec.js
  src/tests/approve.request.spec.js
  src/tests/helper.spec.js
  src/tests/request.model.spec.js
  src/validation/index.js
Labels: Ready For Review

#28 #169113440 edit or delete an accommodation facility
  src/controllers/accommodationController.js
  src/database/migrations/20191001134215-create-accommodation.js
  src/database/models/Accommodations.js
  src/database/seeders/20191023141609-accommodation.js
  src/middlewares/accommodationMiddleware.js
  src/routes/accommodationRoute.js
  src/tests/accommodation.spec.js
  src/tests/mockData/accommodationData.js
  src/tests/testAccomod.spec.js
  src/validation/index.js
Labels: Ready For Review

#34 #169272097 add full name to accommodation facility
  .travis.yml
  src/controllers/role.js
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/models/user.js
  src/database/seeders/20191002082224-User.js
  src/tests/mockData/email.js
  src/tests/mockData/loginMockData.js
  src/tests/mockData/signupMockupData.js
  src/tests/signup.spec.js
  src/tests/testsLogin.spec.js
  src/tests/users.spec.js
  src/utils/sendResult.js
  src/validation/index.js
Labels: Ready For Review

#37 #168781820 Send notification on request approval or rejection
  src/config/index.js
  src/controllers/email.js
  src/controllers/requestController.js
  src/middlewares/requestMiddlware.js
  src/routes/requestRoutes.js
  src/tests/approve.request.spec.js
  src/utils/emailHelper.js
  src/validation/index.js
Labels: Ready For Review

#48 #169418604 add currency to accommodation
  src/controllers/accommodationController.js
  src/database/migrations/20191029110632-add-currency-accommodation.js
  src/database/models/Accommodations.js
  src/tests/accommodation.spec.js
  src/utils/currencies.json
  src/utils/validator.js
  src/validation/index.js
Labels: Ready For Review

#47 #169392340 refactor and rename user controller
  src/controllers/users.controller.js
  src/routes/userRoutes.js
  src/services/user.service.js
  src/tests/helper.spec.js
  src/tests/testsLogin.spec.js
Labels: Ready For Review

#45 #169392375 refactor accommodations
  src/controllers/accommodationController.js
  src/controllers/accommodations.controller.js
  src/controllers/comments.controller.js
  src/controllers/requests.controller.js
  src/middlewares/accommodation.middleware.js
  src/middlewares/request.middlware.js
  src/middlewares/role.middleware.js
  src/middlewares/user.middlware.js
  src/routes/accommodation.route.js
  src/routes/index.js
  src/routes/request.route.js
  src/routes/user.route.js
  src/services/accommodation.service.js
  src/tests/testsLogin.spec.js
Labels: Ready For Review

#50 #169422478 notifications model and table
  src/database/migrations/20191029135947-Notifications.js
  src/database/models/notifications.js
  src/database/models/user.js
  src/database/seeders/20191029143328-Notifications.js
  src/services/notifications.service.js
  src/tests/notification.model.spec.js
Labels: Ready For Review

#53 #169455597 fix rate accommodation feature
  src/database/models/bookingAccommodation.js
Labels: Ready For Review

#43 #169392362 refactor requests
  src/controllers/requests.controller.js
  src/routes/request.route.js
  src/services/email.service.js
  src/services/request.service.js
  src/utils/emailHelper.js
  src/utils/requestUtils.js
  src/validation/signupValidation.js
Labels: Ready For Review

#42 #168781822 remember personal request data
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20191001134213-create-user.js
  src/database/migrations/20191030123820-add_rememberMe.js
  src/database/models/user.js
  src/database/seeders/20191002082224-User.js
  src/routes/requestRoutes.js
  src/tests/request.post.spec.js
  src/utils/helper.js
Labels: Ready For Review
